# Generated by Django 2.2.24 on 2021-09-13 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_load_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Given',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amountDue', models.DecimalField(blank=True, decimal_places=2, max_digits=1000, null=True)),
                ('change', models.DecimalField(blank=True, decimal_places=2, max_digits=1000, null=True)),
            ],
        ),
    ]
